### ISSUE TITLE
TF2 crashing on startup

### ISSUE THREAD

**Issue by qzc110** [crashfort/SourceDemoRender#20]
Whenever I launch tf2 through launcherUI, the game opens briefly and then crashes with the following error.

```
"CvarPtr"
{
    "GetAddressFromJsonPattern"
    {
        "AddressFinder"
        {
            Null pointer
        }
    }
}
SDR: Could not enable module "CvarPtr"
Could not pass stage "Load"
```

**Comment by qzc110** [comment]
I found out that the pattern for cvarptr was wrong for tf2. 

Changing the pattern in the gameconfig.json from

0F 45 C8 89 8D ?? ?? ?? ?? EB ?? 8B 0D ?? ?? ?? ?? FF 77 **14** 8B 01
to
0F 45 C8 89 8D ?? ?? ?? ?? EB ?? 8B 0D ?? ?? ?? ?? FF 77 **??** 8B 01

fixes the crashing on startup, but now tf2 just freezes when I try to record anything.

**Comment by qzc110** [comment]
I got version 28 to work with tf2 just fine now. I guess there's a bug with the audio recording that causes the game to freeze.

**Comment by SirBlockles** [comment]
I'm experiencing this issue with TF2 on v32 of SDR, what did you do to fix it @qzc110?

**Comment by qzc110** [comment]
@SirBlockles Open gameconfig.json and under cvarptr, change the pattern to
`0F 45 C8 89 8D ?? ?? ?? ?? EB ?? 8B 0D ?? ?? ?? ?? FF 77 ?? 8B 01`
then create a file called LauncherUI_UpdateSkip.

**Comment by mrsteyk** [comment]
@qzc110 ik i might be a bit late, but you can fix freezing by redoing ConVars (make them use strings) and removing return in ModuleSUpdateGuts on audowriter firstframe (I believe that all you need to do). You also might want to kinda ignore disable video, but i dont remember most of the things since i fixed it for myself long ago, around the time i made my ConVar issue.

**Comment by crashfort** [comment]
done with svr
