### ISSUE TITLE
d3d11: Could not create shader 'motion_sample_cs.svs'

### ISSUE THREAD

**Issue by kiritobruh** [crashfort/SourceDemoRender#38]
Tried everything out, but it simply won't work because of that error:

```
Starting process
Created process with id 9836 and thread id 7404
Allocating 4096 remote bytes
Remote address: 0x990000
Resuming process
Using game thread 1504
Waiting for libraries:
- hl2.exe
- shaderapidx9.dll
- materialsystem.dll
- engine.dll
- tier0.dll
- client.dll
Libraries loaded, initializing
d3d11: Creating release device
d3d11: Created device with feature level 45056
d3d11: Could not create shader 'motion_sample_cs.svs' (-7ff8ffa9)
Could not create graphics backend
Could not initialize game. Terminating
Initialization failure
```

The game just pops in, start loading and then crashes after that.

**Comment by crashfort** [comment]
Only Windows 10 is supported and/or your hardware is too old to support typed UAV loads with D3D11.3.

**Comment by b1scoito** [comment]
Reopening this since my hardware should support Typed UAV Loads according to this documentation https://microsoft.github.io/DirectX-Specs/d3d/UAVTypedLoad.html

![image](https://user-images.githubusercontent.com/17802984/122888442-424dc180-d318-11eb-95cf-9c2a30fd9155.png)

I get the same error as his.
