### ISSUE TITLE
CS:GO running very slowly and crashing when opening demos

### ISSUE THREAD

**Issue by trudruchocolatemilk** [crashfort/SourceDemoRender#51]
When launching a demo in csgo after I booted it through the exe, it runs very slowly, like barely moving. And when I try to skip forward into the demo, the game freezes and basically crashes. 
Is this an issue on my end or is it a bug? Any help would be appreciated, 
thanks.

**Comment by zer0k-z** [comment]
I am a bit late but I assume that it's because CSGO demos sometimes get corrupted (just insanely slow rather at 1+ second per tick) if they are recorded within one round (which is usually the case with movement servers). Adding an arbitrary `round_start` event to prevent corruption seems to work though.
