### ISSUE TITLE
Override process & arguments

### ISSUE THREAD

**Issue by couleurm** [crashfort/SourceDemoRender#70]
It'd be nice being able to set our own FFmpeg arguments for support for other encoders (e.g I'd like having libx264 yuv444p, not libx264rgb bgr0)

```ini
# If you wish to set your own FFmpeg arguments, leave this empty and use the above if you don't know what you're doing.
override_ffmpeg=-hide_banner -loglevel quiet -f rawvideo -vcodec rawvideo -pix_fmt yuv444p -s %%WIDTH%%x%%HEIGHT -r %%FPS%% -y -i - -threads 0 -vcodec utvideo %%OUTPUT%%
```

**Comment by crashfort** [comment]
It is not so trivial as in your example to support arbitrary arguments, as the data that is sent to ffmpeg must be formatted by the program. If you insert some arguments of a format that you want that the program doesn't have support to format to, then you will not get any result.

Instead in your example, I would rather add a new encoder option in the ini called ``libx264_444`` in order to not create an unbalanced profile where you as the user can't know if that is a valid combination of encoder and pixel format or not. There are tons of possible pixel formats, but the program is not going to have support for hardware acceleration for all of them.

**Comment by crashfort** [comment]
Not relevant anymore with svr_encoder.
